export const theme = {
    textColorLight: '#F1F1F1',
    textColorDark: "#D3D3D3",
    pageBackground: "#F1F1F1",
    mobile: "768px",
    menuBackground: "#b8f2e6",
    navBackground: "#b8f2e6",
    black: "#000000",
    buttonBackground: '#000000',
    buttonTextColor: '#ffffff',
    textColorLightGrey: '#D3D3D3',
    textColorRedAlert: 'red',
    categoryCardBackground: '#ffffff',
    categoryCardColor: '#000000',
    productCardBackground: '#ffffff',
    productCardColor: '#000000',
    checkoutBtnBackground: '#3399FF',
    checkoutBtnColor: '#ffffff',
    removeItemColor: '#808080'
}